Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: Environment Type
        Parameters: 
          - EnvType
      - 
        Label: 
          default: "Instance Configuration"
        Parameters: 
          - EC2InstanceTypeT
          - EC2InstanceTypeP
          - DBInstanceTypeT
          - DBInstanceTypeP
      
      - 
        Label: 
          default: "DB Configuration"
        Parameters: 
          - DBName
          - DBMasterUserName
          - DBMasterPassword
          - DBMultiAZ
          - DeletionProtection
          - DBSubnets
      
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - KeyName
          - SSHLocation
          - EC2Subnet
      
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  EnvType: 
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues: 
      - production
      - test
    ConstraintDescription: must specify production or test.

  EC2InstanceTypeT:
    Description: WebServer EC2 instance type, ignore if you choose Production Env.
    Type: String
    Default: None
    AllowedValues:
      - None 
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge  

  EC2InstanceTypeP:
    Description: WebServer EC2 instance type, ignore if you choose Test Env.
    Type: String
    Default: None
    AllowedValues:
      - None  
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge    
  
  DBInstanceTypeT:
    Description: RDSDB instance type, ignore if you choose Production Env.
    Type: String
    Default: None
    AllowedValues:
      - None 
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge  
  
  DBInstanceTypeP:
    Description: RDSDB instance type, ignore if you choose Test Env.
    Type: String
    Default: None
    AllowedValues: 
      - None 
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.8xlarge
      - db.m5.12xlarge
      - db.m5.16xlarge    

  DBSubnets:
    ConstraintDescription: Must be list of existing subnet Ids
    Description: >-
      At least two existing Subnets in separate Availability Zones in your Virtual
      Private Cloud (VPC)
    Type: 'List<AWS::EC2::Subnet::Id>'
  

  EC2Subnet:
    Description: Choose a subnet to deploy your instance
    Type: AWS::EC2::Subnet::Id
  
  


  DBName:
    Description: Type a name for your DBInstance
    Type: String
    Default: mysqldb
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    MaxLength: '64'
    MinLength: '5'
  DBMasterUserName:
    Description: DB admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Default: root
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBMasterPassword:
    AllowedPattern: '(?=\S)[^@/"\r\n\t\f\s]*'
    ConstraintDescription: 'Min 8 alphanumeric. Cannot contain white space, @, /, "'
    Description: The database admin account password (username is 'root').
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'True'
    Type: String
  DBMultiAZ:
    Description: Standby Instance in different AZ
    Type: String
    AllowedValues:
      - True
      - False
    Default: False
  DeletionProtection:
    Description: Protects the database from being deleted accidentally. While this option is enabled, you can’t delete the database.
    Type: String
    AllowedValues:
        - True
        - False
    Default: False
  
Conditions:
    Prod: !Equals [!Ref EnvType, production]
    Is-Mumbai: !Or [!Equals [!Ref 'AWS::Region', eu-central-1], !Equals [!Ref 'AWS::Region', ap-south-1]]
    Is-Not-Mumbai: !Not [{Condition: Is-Mumbai}]
         

Mappings:
    RegionMap:
      us-east-1:
        AMI: "ami-0ff8a91507f77f867"
      us-west-1:
        AMI: "ami-0bdb828fd58c52235"
      us-west-2:
        AMI: "ami-a0cfeed8"
      eu-west-1:
        AMI: "ami-047bb4163c506cd98"
      sa-east-1:
        AMI: "ami-07b14488da8ea02a0"
      ap-southeast-1:
        AMI: "ami-08569b978cc4dfa10"
      ap-southeast-2:
        AMI: "ami-09b42976632b27e9b"
      ap-northeast-1:
        AMI: "ami-06cd52961ce9f0d85"
      ap-south-1:
        AMI: "ami-0912f71e06545ad88"
      us-east-2:
        AMI: "ami-0b59bfac6be064b78"
      ap-northeast-2:
        AMI: "ami-0a10b2721688ce9d2"
      ca-central-1:
        AMI: "ami-0b18956f"
      eu-central-1:
        AMI: "ami-0233214e13e500f77"
      eu-west-2:
        AMI: "ami-f976839e"
      eu-west-3:
        AMI: "ami-0ebc281c20e89ba4b"
      
      
      
          
        

Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
          - !GetAtt WebServerSecurityGroup.GroupId
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: !If [Prod, !Ref EC2InstanceTypeP, !Ref EC2InstanceTypeT]
      SubnetId: !Ref EC2Subnet
      UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            host_name=`curl -s http://169.254.169.254/latest/meta-data/local-hostname`
            echo "WELCOME TO FEBATECH WEB SERVER $host_name" > /var/www/html/index.html

  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enables web access and allows SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  
  
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !If [Prod, !Ref DBInstanceTypeP, !Ref DBInstanceTypeT] 
      AllocatedStorage: '20'
      Engine: mysql
      EngineVersion: '8.0.20'
      StorageType: gp2
      DBSecurityGroups: 
        - !If [Is-Not-Mumbai, !Ref 'DBInstanceSecurityGroupNM', !Ref 'AWS::NoValue']
      VPCSecurityGroups: !If [Is-Mumbai, [!GetAtt [DBSecurityGroupM, GroupId]],
        !Ref 'AWS::NoValue']
      DBInstanceIdentifier: !Ref DBName
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBMasterPassword
      MultiAZ: !Ref DBMultiAZ
      DeletionProtection: !Ref DeletionProtection
      DBSubnetGroupName: !Ref DBSubnetGroup


  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: RDS Subnet Group
      SubnetIds: !Ref DBSubnets
      

  DBInstanceSecurityGroupNM:
    Type: AWS::RDS::DBSecurityGroup
    Condition: Is-Not-Mumbai
    Properties:
      DBSecurityGroupIngress:
        EC2SecurityGroupName:
          Ref: WebServerSecurityGroup
      GroupDescription: database access
  
  
  DBSecurityGroupM:
    Type: AWS::EC2::SecurityGroup
    Condition: Is-Mumbai
    Properties:
      GroupDescription: This resource will be created when the region is Mumbai
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupName: !Ref WebServerSecurityGroup

